
queue:
  name: Hosted VS2017
steps:
- task: CmdLine@1
  inputs:
    filename: "echo"
    arguments: "hello yaml"
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: true
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    ArtifactName: artifact-$(Build.BuildId)
    ArtifactType: Container
- task: PowerShell@2
  inputs:
    targetType: filePath
filePath: $(System.DefaultWorkingDirectory)/EnvDump.ps1
